### ISSUE TITLE
Append string to tcp uri

### ISSUE THREAD

**Issue by yonatonreid** [darkhelmet/balance#13]
As per our discussion yesterday, id like to append the ip address to the uri being passed to the server instances in the tcp balancer. How do i accomplish that? I can generate the IP but i need to know how to modify the uri

**Comment by yonatonreid** [comment]
Any feedback? Would be greatly appreciated if you can assist with this.

**Comment by darkhelmet** [comment]
Sorry, but I don't think I can help you.

The TCP load balancer in this toy application is incredibly simple. All it does it connect to one of the balanced IPs and pass data back and forth. If you need it to do more than that, you're more that welcome to modify the code, but this project is effectively an unmaintained toy/example project, and shouldn't be used for anything remotely important. I would recommend looking at something like haproxy if you need something more production ready.

I don't think you can make this work seamlessly (only within the TCP stack), but you could implement the [PROXY protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) as nginx, haproxy, and various others do, but you'd want to make that an option as your backend servers would have to support the PROXY protocol. If you're using HTTP, you should probably just use the HTTP balancer instead of TCP. You'll get more even balancing that way anyway.

In addition, I don't have the time or desire to work on this codebase. It's a toy application, and I got it to the point where it did stuff I was happy with, so I'm basically done with it.

**Comment by yonatonreid** [comment]
I think we are miscommunication. I'm not asking you to put any time in the code. I just want to know where i can modify the path that is being sent back and forth so i can append an IP address to the end.

**Comment by darkhelmet** [comment]
But there's no path...it's an IP. It's making a connection to an IP address.

**Comment by yonatonreid** [comment]
http://1.1.1.1:8080/v1/xx/aaa is the full uri. In this case, /v1/xx/aaa is the path i want to modify, I want http://1.1.1.1:8080/v1/xx/aaa/ipaddress. this isnt available to modify? Its passing that path along somewhere.

**Comment by darkhelmet** [comment]
Since you're using HTTP, you should be using the HTTP load balancer, NOT TCP.

Then you can change whatever you want about the request getting proxied by modifying the director function in `http.go`, but if you're trying to ensure the backend server gets the "real IP" of the client, it should already be getting that with the HTTP load balancer since it passes the `X-Real-IP` header.

**Comment by yonatonreid** [comment]
OK I see that. However, when i do a dump of r.Header inside my api server instance method, i do not see `X-Real-IP`

**Comment by yonatonreid** [comment]
and heres my init command : ./src/github.com/darkhelmet/balance/balance http -bind :8080 127.0.0.1:8111 127.0.0.1:8115 127.0.0.1:8117 127.0.0.1:8119 127.0.0.1:8121 127.0.0.1:8123 127.0.0.1:8125 127.0.0.1:8127 127.0.0.1:8129 127.0.0.1:8131 2>/dev/null &

**Comment by yonatonreid** [comment]
Thanks!

**Comment by yonatonreid** [comment]
The problem is i decided to test tcp balancer and im getting results of 293K requests per second versus 35K requests per second on the HTTP Layer. I tested the `X-REAL-IP` and that works great, but if theres a way for me to just mutate the path being sent to the api servers than i can essentially conitnue with the TCP Balancer because for some reason it works well, unless you can tell me why i shouldnt be using a tcp balancer

**Comment by yonatonreid** [comment]
Thanks
